declare class MSCloudSharesControllerDelegate {}
declare class MSCollapsibleHeaderInspectorItemTarget {}
declare class MSColorHexStringTransformerDelegate {}
declare class MSDataSupplierDelegate {}
declare class MSGPUTexture {}
declare class MSInspectorFlowHandlerDelegate {}
declare class MSInspectorTableViewManagerDelegate {}
declare class MSLayerCoordinateSpace {}
declare class NSEnumerator {}
declare class MSInspectorMathValueAdaptorDelegate {}
